name: gigglify_rp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^11.1.0
  dio: ^5.9.0
  envied: ^1.3.8
  equatable: ^2.0.7
  flutter_riverpod: ^3.3.1
  flutter_secure_storage: ^10.0.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.2
  objectbox: ^5.0.4
  objectbox_flutter_libs: any
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^4.0.2
  share_plus: ^13.3.0
  shared_preferences: ^2.5.4

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.8
  google_fonts: ^8.2.0
  ionicons_plus: ^0.2.5
  modal_bottom_sheet: ^3.0.0
  smooth_page_indicator: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.4.0
  build_runner: ^2.10.4
  envied_generator: ^1.3.8
  flutter_gen_runner: ^5.15.0
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  injectable_generator: ^2.9.1
  json_serializable: ^6.11.2
  objectbox_generator: any
  riverpod_generator: ^4.0.3

flutter:
  assets:
    - assets/image/
    - .env
  uses-material-design: true

flutter_gen:
  output: lib/presentation/generated

flutter_intl:
  enabled: true
  arb_dir: lib/presentation/l10n
  output_dir: lib/presentation/l10n/generated

flutter_native_splash: # dart run flutter_native_splash:create
  color: "#ffffff"
  color_dark: "#15022D"
  image: assets/image/logo.png
  image_dark: assets/image/logo.png
  android_12:
    color: "#ffffff"
    color_dark: "#15022D"
    image: assets/image/logo.png
    image_dark: assets/image/logo.png

objectbox:
  output_dir: data/source/local/db
